x-sql-volume:
  &sql-volume
  type: bind
  source: $HOME/mysql/database
  target: /var/lib/mysql
  
x-sql-schema-init:
  &sql-schema-init
  type: bind
  source: $HOME/SigRepo/inst/mysql/schema/init.sql
  target: /docker-entrypoint-initdb.d/init.sql
  
x-difexp-volume:
  &difexp-volume
  type: bind
  source: $HOME/mysql/difexp
  target: /difexp
  
x-sigrepo-volume:
  &sigrepo-volume
  type: bind
  source: $HOME/SigRepo
  target: /SigRepo

services:
  sigrepo-mysql:
    container_name: sigrepo-mysql
    image: sigrepo-mysql:latest
    build:
      context: .
      dockerfile: Dockerfile-mysql
      args:
        - mysql_image=mysql:8.0-bookworm
    env_file:
      - mysql.env
    networks:
      - db-net
    ports:
      - 3306:3306
    restart: always
    volumes:
      - *sql-volume
      - *sql-schema-init  

  sigrepo:
    container_name: sigrepo
    image: sigrepo:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - R_VERSION=4.4.0
    expose:
      - 3838
    restart: always
    command: tail -f /dev/null

  sigrepo-api:
    container_name: sigrepo-api
    image: sigrepo:latest  
    depends_on:
      - sigrepo-mysql
      - sigrepo
    networks:
      - db-net
    ports:
      - 8020:3838
    restart: always
    volumes:
      - *sigrepo-volume
      - *difexp-volume
    entrypoint: ["/bin/bash", "-c", "/SigRepo/inst/api/shiny-server.sh"]

  sigrepo-shiny:
    container_name: sigrepo-shiny
    image: sigrepo:latest
    depends_on:
      - sigrepo-mysql
      - sigrepo-api
      - sigrepo
    networks:
      - db-net
    ports:
      - 8050:3838
    restart: always
    volumes:
      - *sigrepo-volume
    entrypoint: ["/bin/bash", "-c", "/SigRepo/inst/shiny/shiny-server.sh"]

networks:
  db-net:
    external: true   
    
    
