services:
  sigrepo_rstudio_server:
    container_name: sigrepo_rstudio_server
    image: montilab/sigrepo_rstudio:latest
    environment:
      - PASSWORD=SigRepo  
    ports:
      - 7878:8787
    restart: always
    volumes:
      - /montilab-p/SigRepoShiny:/home/rstudio/SigRepoShiny  
      - /montilab-p/OmicSignature:/home/rstudio/OmicSignature
      - /montilab-p/SigRepo:/home/rstudio/SigRepo

networks:
  rstudio_server:
    name: rstudio_server
