version: '3.8'

x-volumes:
  test-sql-volume: &test-sql-volume
    type: bind
    source: /Users/vicna/OneDrive/Documents/SigRepo_install/mysql/test_database
    target: /var/lib/mysql-test

  sql-schema-init: &sql-schema-init
    type: bind
    source: /Users/vicna/OneDrive/Documents/GitHub/SigRepo/inst/mysql/schema/init.sql
    target: /docker-entrypoint-initdb.d/init.sql

services:
  sigrepo-test-mysql:
    container_name: sigrepo-test-mysql
    image: montilab/sigrepo-mysql:latest
    env_file:
      - mysql.env
    networks:
      - db-net
    ports:
      - "3307:5432"
    restart: always
    volumes:
      - *test-sql-volume
      - *sql-schema-init

networks:
  db-net:
