services:
  mysql:
    container_name: mysql
    image: montilab/sigrepo_mysql:latest
    volumes:
      - /montilab-p/mysql/conf.d:/etc/mysql/conf.d
      - /montilab-p/mysql/database:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'sigrepo'
      MYSQL_ROOT_HOST: '%'
