---
title: "How to run SigRepo Shiny within a Docker Environment"
output: rmarkdown::html_document
vignette: >
  %\VignetteIndexEntry{How to run SigRepo within a Docker Environment}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Software requirements

- Git version >= 2.21
- Docker version >= 20.10

Don't have Git installed, see [Git Guides](https://github.com/git-guides/install-git)

Don't have Docker installed, download a [Docker Engine](https://docs.docker.com/engine/install/) that is compatible with your machine

**NOTE:** may need to restart your computer for Docker to kicks-in

- Check if Docker is installed 

```bash
docker --version
```

- Check if Docker Compose is installed

```bash
docker compose version
```

## Set Up Mysql Database

- Explore [how to set-up SigRepo database and its schema via Docker]() for more details

## Run SigRepo Shiny Dashboard

1. Clone this repository and navigate to **SigRepo** folder

```bash
git clone https://github.com/montilab/SigRepo
cd SigRepo
```

2. Create an **.Renviron** file to store credentials to log into a remote SigRepo Database

```text
DBNAME = "database_name"
HOST = "host_ip_address"
PORT = "port"
USER = "username"
PASSWORD = "password"
```

3. Create a **docker-compose-sigrepo-shiny.yml** to configure how to build Sigrepo Shiny image and container.

```text
services:
  sigrepo-shiny:
    container_name: sigrepo-shiny
    image: sigrepo-shiny:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - R_VERSION=4.4.0
    networks:
      - db-net
    ports:
      - 8050:3838
    restart: always
    volumes:
      - /montilab-p/Sigrepo/.Renviron:/root/.Renviron
    command: tail -f /dev/null 
```

4. Start Sigrepo Shiny containers

```bash
docker compose -f docker-compose-sigrepo-shiny.yml up -d
```

**`-f`**: name of the docker compose file <br>
**`-d`**: run container in detached mode <br>

5. Check if the container is built successfully

```bash
docker ps


CONTAINER ID   IMAGE                  COMMAND                    CREATED        STATUS        PORTS                    NAMES
b37b6b19c4e8   sigrepo-shiny:latest   "/bin/bash -c /user/..."   5 hours ago    Up 5 hours    0.0.0.0:8050->3838/tcp   sigrepo-shiny
```

Based on the output above, the `sigrepo-shiny` dashboard is published on port **8050** on the host machine, and **3838** is the port of where the `sigrepo-shiny` is published inside the Docker container. Noted that all requests that are made to the host machine will be automatically redirected to the Docker container where the Shiny app is launched and deployed.

6. Access `SigRepo` dashboard on your localhost

Using your preferred web browser, type in http://localhost:8050 and see if `SigRepo` dashboard is indeed hosted there.

<br>

Any questions or issues? Please report them on our [github issues](https://github.com/montilab/SigRepo/issues).


