---
title: "Frequently asked questions"
output: rmarkdown::html_document
vignette: >
  %\VignetteIndexEntry{Frequently asked questions}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{css, echo=FALSE}
thead {
  font-weight: bold;
}

thead, td {
  padding: 5px;
  border: 1px solid black
}
```

## How do I get help?

**SigRepo_Server** is under active development. If you need help, would like to contribute, or simply want to talk about the project with like-minded individuals, we have a number of open channels for communication.

- Send us an email at [sigrepo@bu.edu](mailto:sigrepo@bu.edu)

- To report bugs or file feature requests, use the [issue tracker on Github](https://github.com/montilab/SigRepo_Server/issues).

- To contribute code, submit a [pull request on Github](https://github.com/montilab/SigRepo_Server/pulls).

## How to verify all containers are built and run successfully

```bash
docker compose ps


CONTAINER ID   IMAGE                           COMMAND                  CREATED          STATUS          PORTS                               NAMES
9210e8d30506   montilab/sigrepo:latest         "/bin/bash -c /SigRe…"   2 minutes ago    Up 2 minutes    0.0.0.0:8050->3838/tcp              sigrepo-shiny
57076db95606   montilab/sigrepo:latest         "/bin/bash -c /SigRe…"   2 minutes ago    Up 2 minutes    0.0.0.0:8020->3838/tcp              sigrepo-api
77ca9528cb3b   montilab/sigrepo-mysql:latest   "docker-entrypoint.s…"   26 minutes ago   Up 14 minutes   0.0.0.0:3306->3306/tcp, 33060/tcp   sigrepo-mysql
```

## Docker Compose operations

<table>
<thead>
  <tr>
    <td>Command</td>
    <td>Description</td>
  </tr>
</thead>
<tbody>

  
  <tr>
    <td><a target="_blank" href="https://docs.docker.com/engine/reference/commandline/compose_build/">docker compose build</a></td>
    <td>Build or rebuild services</td>
  </tr>

  
  <tr>
    <td><a target="_blank" href="https://docs.docker.com/engine/reference/commandline/compose_config/">docker compose config</a></td>
    <td>Parse, resolve and render compose file in canonical format</td>
  </tr>

  
  <tr>
    <td><a target="_blank" href="https://docs.docker.com/engine/reference/commandline/compose_cp/">docker compose cp</a></td>
    <td>Copy files/folders between a service container and the local filesystem</td>
  </tr>

  
  <tr>
    <td><a target="_blank" href="https://docs.docker.com/engine/reference/commandline/compose_create/">docker compose create</a></td>
    <td>Creates containers for a service.</td>
  </tr>

  
  <tr>
    <td><a target="_blank" href="https://docs.docker.com/engine/reference/commandline/compose_down/">docker compose down</a></td>
    <td>Stop and remove containers, networks</td>
  </tr>

  
  <tr>
    <td><a target="_blank" href="https://docs.docker.com/engine/reference/commandline/compose_events/">docker compose events</a></td>
    <td>Receive real time events from containers.</td>
  </tr>

  
  <tr>
    <td><a target="_blank" href="https://docs.docker.com/engine/reference/commandline/compose_exec/">docker compose exec</a></td>
    <td>Execute a command in a running container.</td>
  </tr>

  
  <tr>
    <td><a target="_blank" href="https://docs.docker.com/engine/reference/commandline/compose_images/">docker compose images</a></td>
    <td>List images used by the created containers</td>
  </tr>

  
  <tr>
    <td><a target="_blank" href="https://docs.docker.com/engine/reference/commandline/compose_kill/">docker compose kill</a></td>
    <td>Force stop service containers.</td>
  </tr>

  
  <tr>
    <td><a target="_blank" href="https://docs.docker.com/engine/reference/commandline/compose_logs/">docker compose logs</a></td>
    <td>View output from containers</td>
  </tr>

  
  <tr>
    <td><a target="_blank" href="https://docs.docker.com/engine/reference/commandline/compose_ls/">docker compose ls</a></td>
    <td>List running compose projects</td>
  </tr>

  
  <tr>
    <td><a target="_blank" href="https://docs.docker.com/engine/reference/commandline/compose_pause/">docker compose pause</a></td>
    <td>Pause services</td>
  </tr>

  
  <tr>
    <td><a target="_blank" href="https://docs.docker.com/engine/reference/commandline/compose_port/">docker compose port</a></td>
    <td>Print the public port for a port binding.</td>
  </tr>

  
  <tr>
    <td><a target="_blank" href="https://docs.docker.com/engine/reference/commandline/compose_ps/">docker compose ps</a></td>
    <td>List containers</td>
  </tr>

  
  <tr>
    <td><a target="_blank" href="https://docs.docker.com/engine/reference/commandline/compose_pull/">docker compose pull</a></td>
    <td>Pull service images</td>
  </tr>

  
  <tr>
    <td><a target="_blank" href="https://docs.docker.com/engine/reference/commandline/compose_push/">docker compose push</a></td>
    <td>Push service images</td>
  </tr>

  
  <tr>
    <td><a target="_blank" href="https://docs.docker.com/engine/reference/commandline/compose_restart/">docker compose restart</a></td>
    <td>Restart service containers</td>
  </tr>

  
  <tr>
    <td><a target="_blank" href="https://docs.docker.com/engine/reference/commandline/compose_rm/">docker compose rm</a></td>
    <td>Removes stopped service containers</td>
  </tr>

  
  <tr>
    <td><a target="_blank" href="https://docs.docker.com/engine/reference/commandline/compose_run/">docker compose run</a></td>
    <td>Run a one-off command on a service.</td>
  </tr>

  
  <tr>
    <td><a target="_blank" href="https://docs.docker.com/engine/reference/commandline/compose_start/">docker compose start</a></td>
    <td>Start services</td>
  </tr>

  
  <tr>
    <td><a target="_blank" href="https://docs.docker.com/engine/reference/commandline/compose_stop/">docker compose stop</a></td>
    <td>Stop services</td>
  </tr>

  
  <tr>
    <td><a target="_blank" href="https://docs.docker.com/engine/reference/commandline/compose_top/">docker compose top</a></td>
    <td>Display the running processes</td>
  </tr>

  
  <tr>
    <td><a target="_blank" href="https://docs.docker.com/engine/reference/commandline/compose_unpause/">docker compose unpause</a></td>
    <td>Unpause services</td>
  </tr>

  
  <tr>
    <td><a target="_blank" href="https://docs.docker.com/engine/reference/commandline/compose_up/">docker compose up</a></td>
    <td>Create and start containers</td>
  </tr>

  
  <tr>
    <td><a target="_blank" href="https://docs.docker.com/engine/reference/commandline/compose_version/">docker compose version</a></td>
    <td>Show the Docker Compose version information</td>
  </tr>

</tbody>
</table>
