---
title: "Initiate Sigrepo Database on a Remote Server"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Initiate Sigrepo on a Remote Server}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Software requirements

- Git version >= 2.21
- Docker version >= 20.10

Don't have Git installed, see [Git Guides](https://github.com/git-guides/install-git)

Don't have Docker installed, download a [Docker Engine](https://docs.docker.com/engine/install/) that is compatible with your machine

**NOTE:** You may need to restart your computer for Docker to take effect.

- Check if Docker is installed successfully

```bash
docker --version
```

- Check if Docker Compose is installed successfully

```bash
docker compose version
```

## Set-up

### 1. SSH to your remote server

```bash
ssh <user_name>@<remote_ip_address>
```

### 2. Clone this repository to your `$HOME` directory and navigate to `SigRepo` folder

```bash
cd $HOME
git clone https://github.com/montilab/SigRepo
cd SigRepo
```

### 3. Create a `mysql.env` file to initiate admin users in the database

```bash
nano mysql.env
```

- Copy the configurations below to **mysql.env** file

```text
MYSQL_DATABASE='sigrepo'
MYSQL_USER='montilab'
MYSQL_PASSWORD='sigrepo'
MYSQL_ROOT_PASSWORD='sigrepo'
MYSQL_ROOT_HOST='%'
```

__PARAMETERS:__

- `MYSQL_DATABASE`: Name of the database <br>
- `MYSQL_USER`: Name of a super user in the database (e.g., having `sudo` privileges) <br>
- `MYSQL_PASSWORD`: Password for the super user <br>
- `MYSQL_ROOT_PASSWORD`: Password for root user <br>
- `MYSQL_ROOT_HOST`: Database access. '%' gives access to everyone. <br>

__IMPORTANT NOTES:__

- We are using a MySQL image in **DockerHub** as base image to initiate the database. See the official image [here](https://hub.docker.com/_/mysql) for additional environments that one can use.

- The environment variables above are just dummy values. Please change them to more encrypted values when deploying to production.

### 4. Create a MySQL `database` directory in your `$HOME` directory to store database tables and its schema

```bash
mkdir -p /$HOME/mysql/database
```

### 5. Create a `difexp` directory in your `$HOME` directory to store differential expression from the uploaded signatures using the `SigRepo` package and its API.

```bash
mkdir -p /$HOME/mysql/difexp
```

### 6. Create a network called `"db-net"` to connect MySQL Server to SigRepo's API internally.

```bash
docker network create -d bridge db-net
```

### 7. Edit `docker-compose-dockerhub.yml` to configure how to build the MySQL image and run its container.

__IMPORTANT NOTES:__

- **MAKE SURE** to map the `database` directory you created in (**3**) to the container `/var/lib/mysql` directory. <br>
- **MAKE SURE** to map the `difexp` directory you created in (**4**) to the container `/difexp` directory. <br>
- **MAKE SURE** to map the initiation script (`init.sql`) which stored in `SigRepo/inst/mysql/schema` directory to the container `/docker-entrypoint-initdb.d/init.sql` directory. This script will initiate the MySQL database and its schema. <br>
- **MAKE SURE** to map the `SigRepo` directory to the container `/SigRepo` directory in order to use a suite of functions in the `SigRepo` package to interact with the database. <br>

```text
services:
  sigrepo-mysql:
    container_name: sigrepo-mysql
    image: montilab/sigrepo-mysql:latest
    env_file:
      - mysql.env
    networks:
      - db-net
    ports:
      - 3306:3306
    restart: always
    volumes:
      - $HOME/mysql/database:/var/lib/mysql:rw
      - $HOME/SigRepo/inst/mysql/schema/init.sql:/docker-entrypoint-initdb.d/init.sql:rw

  sigrepo-api:
    container_name: sigrepo-api
    image: montilab/sigrepo:latest
    depends_on:
      - sigrepo-mysql
    networks:
      - db-net
    ports:
      - 8020:3838
    restart: always
    volumes:
      - $HOME/SigRepo:/SigRepo
      - $HOME/mysql/difexp:/difexp:rw
    entrypoint: ["/bin/bash", "-c", "/SigRepo/inst/api/shiny-server.sh"]
    
  sigrepo-shiny:
    container_name: sigrepo-shiny
    image: montilab/sigrepo:latest
    depends_on:
      - sigrepo-mysql
      - sigrepo-api
    networks:
      - db-net
    ports:
      - 8050:3838
    restart: always
    volumes:
      - $HOME/SigRepo:/SigRepo
    entrypoint: ["/bin/bash", "-c", "/SigRepo/inst/shiny/shiny-server.sh"]
            
networks:
  db-net:
    external: true
```

### 8. Build the MySQL image and run its container

```bash
docker compose -f docker-compose-dockerhub.yml up -d
```

**`-d`**: run container in detached mode <br>

### 9. Check if the container is built successfully

```bash
docker ps


CONTAINER ID   IMAGE                           COMMAND                  CREATED       STATUS       PORTS                                                  NAMES
95ac83ff67b6   montilab/sigrepo-mysql:latest   "docker-entrypoint.s…"   2 weeks ago   Up 2 weeks   0.0.0.0:3306->3306/tcp, :::3306->3306/tcp, 33060/tcp   sigrepo-mysql
70c2dae8511d   montilab/sigrepo:latest         "/bin/bash -c /SigRe…"   2 weeks ago   Up 2 weeks   0.0.0.0:8020->3838/tcp, [::]:8020->3838/tcp            sigrepo-api
0472a25885b6   montilab/sigrepo:latest         "/bin/bash -c /SigRe…"   2 weeks ago   Up 2 weeks   0.0.0.0:8050->3838/tcp, [::]:8050->3838/tcp            sigrepo-shiny
```

### 10. Get ip address of `sigrepo-mysql` container in order to link MySQL Server to SigRepo's API internally

```
docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' sigrepo-mysql 

172.18.0.2
```

### 10. Get the host name of the server

```
hostname
```

or

```
uname -n
```

For example: 142.93.67.157

### 11. Create an **.Renviron** file with all credentials to access the database.

```bash
touch .Renviron
nano .Renviron
```

- Copy the configurations below to the **.Renviron** file

```
DBNAME = "sigrepo"
HOST = "142.93.67.157"
HOST_DB_NET = "172.18.0.2"
PORT = 3306
API_PORT = 8020
USER = "root"
PASSWORD = "sigrepo"
```

### 12. When an environment file is altered or added, it is `IMPORTANT` to restart the containers in order for them to pick up the newly added/edited values.

```bash
docker compose -f docker-compose-dockerhub.yml restart
```

### 13. Finally, open `SigRepo.Rproj` with your `RStudio Server`. Here, we will use the `SigRepo` package to upload an omic signature to the newly created database.

- Load packages with `devtools`

```
# Load devtools package
library(devtools)

# Load SigRepo package
devtools::load_all()

# Load tidyverse package
library(tidyverse)

# Load OmicSignature package
library("OmicSignature")
```

- Create a handler to establish connection to the database using environment variables created in (11)

```
# Create a connection handler
conn_handler <- SigRepo::newConnHandler(
  dbname = Sys.getenv("DBNAME"), 
  host = Sys.getenv("HOST"), 
  port = as.integer(Sys.getenv("PORT")), 
  user = Sys.getenv("USER"), 
  password = Sys.getenv("PASSWORD")
)
```

- Create an omic signature using **OmicSignature** package

```
# Create signature metadata
metadata <- base::list(
  # required attributes:
  signature_name = "Myc_reduce_mice_liver_24m",
  organism = "Mus Musculus",
  direction_type = "bi-directional",
  assay_type = "transcriptomics",
  phenotype = "Myc_reduce",
  
  # optional and recommended:
  covariates = "none",
  description = "mice MYC reduced expression",
  platform = "GPL6246", # use GEO platform ID
  sample_type = "liver", # use BRENDA ontology
  
  # optional cut-off attributes.
  # specifying them can facilitate the extraction of signatures.
  logfc_cutoff = NULL,
  p_value_cutoff = NULL,
  adj_p_cutoff = 0.05,
  score_cutoff = 5,
  
  # other optional built-in attributes:
  keywords = c("Myc", "KO", "longevity"),
  cutoff_description = NULL,
  author = NULL,
  PMID = 25619689,
  year = 2015,
  
  # example of customized attributes:
  others = list("animal_strain" = "C57BL/6")
)

# Create difexp object
difexp <- base::readRDS(file.path(system.file("extdata", package = "OmicSignature"), "difmatrix_Myc_mice_liver_24m.rds")) %>% dplyr::rename(feature_name = ensembl)
colnames(difexp) <- OmicSignature::replaceDifexpCol(colnames(difexp))

# Create signature object
signature <- difexp %>%
  dplyr::filter(abs(score) > metadata$score_cutoff & adj_p < metadata$adj_p_cutoff) %>%
  dplyr::select(probe_id, feature_name, score) %>%
  dplyr::mutate(direction = ifelse(score > 0, "+", "-"))

# Create signature object 
omic_signature <- OmicSignature::OmicSignature$new(
  metadata = metadata,
  signature = signature,
  difexp = difexp
)
```

- Use **SigRepo::addSignature()** function to add the signature to the database 

```
# Add signature to database
SigRepo::addSignature(
  conn_handler = conn_handler,        
  omic_signature = omic_signature,    
  visibility = FALSE,                
  return_signature_id = FALSE,        
  verbose = TRUE                      
)
```
