services:
  sigrepo_api:
    container_name: sigrepo_api
    image: montilab/sigrepo_api:latest
    ports:
      - 8020:38380
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - /montilab-p/SigRepoR:/srv/shiny-server
      
networks:
  sigrepo_api:
    name: sigrepo_api