--
-- Table structure for `signatures`
--
CREATE TABLE `signatures` (
  `signature_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `signature_name` VARCHAR(255) NOT NULL,
  `organism_id` INT UNSIGNED NOT NULL,
  `direction_type` SET("uni-directional", "bi-directional", "categorical") NOT NULL,
  `assay_type` SET("transcriptomics", "proteomics", "metabolomics", "methylomics", "genetic_variations", "dna_binding_sites") NOT NULL,
  `phenotype_id` INT UNSIGNED NOT NULL,
  `platform_id` INT UNSIGNED NOT NULL,
  `sample_type_id` INT UNSIGNED NOT NULL,
  `covariates` TEXT DEFAULT NULL,
  `description` TEXT DEFAULT NULL,
  `score_cutoff` NUMERIC(10, 8) DEFAULT NULL,
  `logfc_cutoff` NUMERIC(10, 8) DEFAULT NULL,
  `p_value_cutoff` NUMERIC(10, 8) DEFAULT NULL,
  `adj_p_cutoff` NUMERIC(10, 8) DEFAULT NULL,
  `cutoff_description` TEXT DEFAULT NULL,
  `keywords` TEXT DEFAULT NULL,
  `PMID` INT DEFAULT NULL,
  `year` INT DEFAULT NULL,
  `others` TEXT DEFAULT NULL,
  `has_difexp` BOOL DEFAULT 0,
  `num_of_difexp` INT DEFAULT NULL,
  `num_up_regulated` INT DEFAULT NULL,
  `num_down_regulated` INT DEFAULT NULL,
  `user_name` VARCHAR(255) NOT NULL,
  `date_created` DATETIME DEFAULT CURRENT_TIMESTAMP,  
  `visibility` BOOL DEFAULT 0,  
  `signature_hashkey` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`signature_id`),
  UNIQUE (`signature_name`, `user_name`),
  FOREIGN KEY (`organism_id`) REFERENCES organisms (`organism_id`),
  FOREIGN KEY (`phenotype_id`) REFERENCES phenotypes (`phenotype_id`),
  FOREIGN KEY (`platform_id`) REFERENCES platforms (`platform_id`),
  FOREIGN KEY (`sample_type_id`) REFERENCES sample_types (`sample_type_id`),
  FOREIGN KEY (`user_name`) REFERENCES users (`user_name`),
  CHECK (`has_difexp` IN (0,1)),
  CHECK (`visibility` IN (0,1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
